---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: _gigs
  label: Gigs
  create: all
  match: "**/*"
  templates:
  - gigs
- type: directory
  path: _stories
  label: stories
  create: all
  match: "**/*"
  templates:
  - stories
- type: directory
  path: _services
  label: Services
  create: all
  match: "**/*"
  templates:
  - service
- type: directory
  path: _partners
  label: Partners
  create: all
  match: "**/*"
  templates:
  - partner
- type: directory
  path: _events
  label: Events
  create: all
  match: "**/*"
  templates:
  - event
- type: jekyll-posts
  label: Posts
  create: all
  templates:
  - posts
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: "//app/_site"
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: carolineolivia94/jekyll-plus-plus
  mount_path: "//app"
  working_dir: "//app"
  instant_preview_command: jekyll serve --drafts --unpublished --future --port 8080
    --host 0.0.0.0 -d _site --watch
