---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: _services
  label: Services
  create: all
  match: "**/*"
- type: directory
  path: _partners
  label: Partners
  create: all
  match: "**/*"
- type: directory
  path: _events
  label: Events
  create: all
  match: "**/*"
- type: directory
  path: _stories
  label: Stories
  create: all
  match: "**/*"
- type: jekyll-posts
  label: Posts
  create: all
  match: "**/*"
- type: directory
  path: _pages
  label: Pages
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: docker run -it  --rm  --pid=host -v /$(pwd)://app:rw
    --workdir //app  --publish 80:4000
  preview_docker_image: carolineolivia94/jekyll-plus-plus
  mount_path: _site
  working_dir: "."
  instant_preview_command: jekyll serve --config _config.yml,_dev_config.yml
