---
label: Service
hide_body: false
fields:
- type: text
  name: title
  label: title
  description: Titlen på din service
- type: text
  name: icon
  label: icon
  description: Font awesome icon https://fontawesome.com/
- type: text
  name: button
  label: button
  description: Navnet på den button der kommer hvis der ikke er en google form
- type: boolean
  name: show
  label: show
  description: Toggle for om denne service skal visses eller ej
- type: textarea
  name: form
  label: form
  description: Google form linket
- type: number
  name: form-height
  label: form-height
  description: Form height får når du clicker på "send" knappen og så på <> knappen
- type: boolean
  name: change
  label: change
  description: Bruges til at bestemme om der bruges en google form eller en knap til
    internt link
- type: text
  name: internal-link
  label: internal-link
  description: Det interne link der bruges til knappen hvis der ikke er en google
    form
- type: text
  name: lang-id
  label: sprog id
  description: Dette felt er til at forbinde de to services som har forkelige sprog. Dette tal skal stemme overens med den anden service og være unikt. Brug '' rund om talet
- type: text
  name: lang
  label: sprog
  description: Bruges til at vægle hviklet sprog der er på din service. Brug gb for engelsk og dk for dansk. Se mere here https://flagicons.lipis.dev/
pages:
- _services/din-it-afdeling-i-vores-hus.md
