---
label: Service
hide_body: false
fields:
- type: text
  name: title
  label: title
  description: Titlen på din service
- type: text
  name: icon
  label: icon
  description: Font awesome icon
- type: text
  name: button
  label: button
  description: Navnet på den button der kommer hvis der ikke er en google form
- type: boolean
  name: operational
  label: operational
  description: Toggle for om services er klar til at gå live
- type: textarea
  name: form
  label: form
  description: Google form linket
- type: number
  name: form-height
  label: form-height
  description: Form height får når du clicker på "send" knappen og så på <> knappen
- type: boolean
  name: change
  label: change
  description: Bruges til at bestemme om der bruges en google form eller en knap til
    internt link
- type: text
  name: internal-link
  label: internal-link
  description: Det interne link der bruges til knappen hvis der ikke er en google
    form
